### ISSUE TITLE
Cannot combine two conditions in novelty

### ISSUE THREAD

**Issue by arichiardi** [juxt/mach#15]
Hey folks!
After conversation on Slack as well, I am opening this because it seems like the `novelty` key cannot accept functions (maybe, maybe there issue is something different). I have a repro here: https://github.com/arichiardi/lumo-repros

With:

```
novelty (fn [] (or (not (mach.core/file-exists? product))
                   (not (mach.core/modified-since product #ref [machfile]))))
```
This happens:

```
$ rm cp package.json
$ mach cp
Nothing to do!
```

I expect the classpath to be created (no file there).

Thanks as usual :smile:

**Comment by jonpither** [comment]
You don't need to wrap it in a function, try this:

````
novelty (or (not (mach.core/file-exists? product))
                  (not (mach.core/modified-since product #ref [machfile])))
````
