### ISSUE TITLE
`lumo` not present in `.bin`

### ISSUE THREAD

**Issue by bhb** [juxt/mach#30]
Repro:

1. `sudo npm install -g @juxt/mach lumo-cljs`
2. `mach`

Expected: Error message about missing Machfile
Actual: Error is `/Users/bbrinck/.nvm/versions/node/v6.6.0/bin/mach: line 14: /Users/bbrinck/.nvm/versions/node/v6.6.0/lib/node_modules/@juxt/mach/node_modules/.bin/lumo: No such file or directory`

Version info:

```
> node -v
v6.6.0
> npm -v
4.5.0
> npm -g ls @juxt/mach lumo-cljs
/Users/bbrinck/.nvm/versions/node/v6.6.0/lib
└─┬ @juxt/mach@1.4.1
  └── lumo-cljs@1.4.1
```

**Comment by SevereOverfl0w** [comment]
Can you do `ls -las /Users/bbrinck/.nvm/versions/node/v6.6.0/lib/node_modules/@juxt/mach/node_modules/.bin/lumo`?

**Comment by bhb** [comment]
Weird, I just did an uninstall with `sudo npm uninstall -g @juxt/mach lumo-cljs` and then did `sudo npm install -g @juxt/mach lumo-cljs` again. Now it works. I thought I did exactly that before, but I must have missed something. Sorry for the confusion!

FWIW, before I did the full uninstall and reinstall, here is the contents of `.bin`

```
> ls -las /Users/bbrinck/.nvm/versions/node/v6.6.0/lib/node_modules/@juxt/mach/node_modules/.bin/
ls: /Users/bbrinck/.nvm/versions/node/v6.6.0/lib/node_modules/@juxt/mach/node_modules/.bin/: No such file or directory
```

Here is the full contents of node modules

```
> tree -a /Users/bbrinck/.nvm/versions/node/v6.6.0/lib/node_modules/@juxt/mach/node_modules
/Users/bbrinck/.nvm/versions/node/v6.6.0/lib/node_modules/@juxt/mach/node_modules
├── ini
│   ├── LICENSE
│   ├── README.md
│   ├── ini.js
│   └── package.json
├── os-tmpdir
│   ├── index.js
│   ├── license
│   ├── package.json
│   └── readme.md
├── tmp
│   ├── LICENSE
│   ├── README.md
│   ├── lib
│   │   └── tmp.js
│   └── package.json
└── toposort
    ├── .npmignore
    ├── .travis.yml
    ├── License
    ├── Makefile
    ├── README.md
    ├── component.json
    ├── graph.svg
    ├── index.js
    ├── package.json
    └── test.js
```

Feel free to close this out, since I can no longer repro.

**Comment by SevereOverfl0w** [comment]
Occasionally lumo fails to install, so it may have been that. I'll keep an eye open to it happening again!

On 14 May 2017 23:28:10 BST, Ben Brinckerhoff <notifications@github.com> wrote:
>Weird, I just did an uninstall with `sudo npm uninstall -g @juxt/mach
>lumo-cljs` and then did `sudo npm install -g @juxt/mach lumo-cljs`
>again. Now it works. I thought I did exactly that before, but I must
>have missed something. Sorry for the confusion!
>
>FWIW, before I did the full uninstall and reinstall, here is the
>contents of `.bin`
>
>```
>> ls -las
>/Users/bbrinck/.nvm/versions/node/v6.6.0/lib/node_modules/@juxt/mach/node_modules/.bin/
>ls:
>/Users/bbrinck/.nvm/versions/node/v6.6.0/lib/node_modules/@juxt/mach/node_modules/.bin/:
>No such file or directory
>```
>
>Here is the full contents of node modules
>
>```
>> tree -a
>/Users/bbrinck/.nvm/versions/node/v6.6.0/lib/node_modules/@juxt/mach/node_modules
>/Users/bbrinck/.nvm/versions/node/v6.6.0/lib/node_modules/@juxt/mach/node_modules
>├── ini
>│   ├── LICENSE
>│   ├── README.md
>│   ├── ini.js
>│   └── package.json
>├── os-tmpdir
>│   ├── index.js
>│   ├── license
>│   ├── package.json
>│   └── readme.md
>├── tmp
>│   ├── LICENSE
>│   ├── README.md
>│   ├── lib
>│   │   └── tmp.js
>│   └── package.json
>└── toposort
>    ├── .npmignore
>    ├── .travis.yml
>    ├── License
>    ├── Makefile
>    ├── README.md
>    ├── component.json
>    ├── graph.svg
>    ├── index.js
>    ├── package.json
>    └── test.js
>```
>
>Feel free to close this out, since I can no longer repro.
>
>
>
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/juxt/mach/issues/30#issuecomment-301344269

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by anmonteiro** [comment]
Lumo failing to install should happen much less frequently starting version 1.5.0

**Comment by jonpither** [comment]
Closing
