### ISSUE TITLE
Document that Aero needs to be a dependency and how to include it

### ISSUE THREAD

**Issue by arichiardi** [juxt/mach#8]
I was trying `mach target` from the repo but it fails:

```
#error {:message No such namespace: aero.core, could not locate aero/core.cljs, aero/core.cljc, or Closure namespace "aero.core", :data {:tag :cljs/analysis-error}}
```

Probably now that the dependency is gone there will need to be a way to import it from clojars.

Thanks folks for this tool, I am going to experiment with it (on the previous tag) :smile:

**Comment by jonpither** [comment]
Fixed by #12
